# Generated by Django 5.2.8 on 2025-11-10 19:34

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='E.164 format preferred', null=True))),
                ('address_line1', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('address_line2', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('postal_code', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('city', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('region', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('country', models.CharField(default='SE', max_length=2)),
                ('language', models.CharField(default='en', max_length=8)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
