# Generated by Django 5.2.8 on 2025-11-09 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('region', models.CharField(blank=True, help_text='E.g., län, fylke, landsdel', max_length=100, verbose_name='Region/State')),
                ('country', models.CharField(default='SE', help_text='ISO 3166-1 alpha-2 code (SE, NO, DK, FI, IS)', max_length=2, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'indexes': [models.Index(fields=['country', 'city'], name='core_addres_country_46bfbe_idx'), models.Index(fields=['postal_code'], name='core_addres_postal__e6c232_idx')],
            },
        ),
    ]
